apiVersion: v1
kind: Template
metadata:
  labels:
    app: hello-openshift
  name: hello-openshift
  namespace: test-gitops-operator
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: hello-openshift
  spec:
    serviceAccount: gitops
    serviceAccountName: gitops
    containers:
    - image: openshift/hello-openshift:latest
      imagePullPolicy: Always
      name: hello-openshift
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 8888
        protocol: TCP
